import { Container } from '@mui/material';
import Head from 'next/head';
import { FC } from 'react';
import { DefaultLayout } from 'layout/DefaultLayout';
import { Header } from './Header';
import { AboutUs } from './AboutUs';
import { Service } from './Service';
import { Location } from './Location';

export const LandingPage: FC = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <DefaultLayout>
      <Header />
      <Container>
        <AboutUs />
        <Service />
        <Location />
      </Container>
    </DefaultLayout>

  </div>
);
