export type PersonalDataField =
| 'user_name'
| 'age'
| 'initial_weight'
| 'height'
| 'email'
| 'phone_number'
| 'city'
| 'ins_handler'
| 'consent'

export type DietDataField =
| 'intolerance'
| 'least_favorite_food'
| 'favorite_food'
| 'food_schedule'
| 'food_description'
| 'getup_time'
| 'job_description'
| 'gym_time'
| 'training_duration'
| 'training_frecuency'
| 'supplementation'

export type IntestinalDataField =
| 'haveConstipation'
| 'haveFecesOdor'
| 'haveDigestionProblem'
| 'haveGastritis'
| 'haveIntestinalPain'
| 'havePeriodPain'
| 'isChillySensitive'
| 'haveLiquidRetention'
| 'haveNausea'
| 'haveSleepProblem'
| 'isTiredGetup'
| 'haveProcessedFoodDaily'
| 'haveCramps'
| 'haveBellyFat'
| 'canTellHungerOrAnxiety'
| 'haveHeadacheAfterMeal'
| 'haveNeedOfSweet'
| 'eatForBoring'
| 'isHungryEvery3Hours'
| 'takeMedication'
| 'diagnosticTest'
| 'antibioticUse'
| 'eatAlone'
| 'dietHistory'
| 'whoPrepareTheFood'
| 'eatingTime'
| 'familyIllnessHistory'

export type CurrentFoodHabitDataField = 'current_food_habit'

export type PathologiesDataField = 'pathologies'

export type RelatedDataField = 'relatedData'

export type GoalDataField = 'goal'
