import { AppBar, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Header } from './Header';
import { FC } from 'react';
import { TopBar } from './TopBar';



export const LandingPage: FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <TopBar/>
       <Header/>
      </main>

    </div>
  )
}

