import { Container } from '@mui/material';
import Head from 'next/head';
import { FC } from 'react';
import { Header } from './Header';
import { TopBar } from './TopBar';
import { AboutUs } from './AboutUs';
import { Service } from './Service';
import { Location } from './Location';

export const LandingPage: FC = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <TopBar />
      <Header />
      <Container>
        <AboutUs />
        <Service />
        <Location />
      </Container>
    </main>

  </div>
);
