import { AppBar, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { StyledAppBar, StyledHeader, StyledHeaderImg, StyledHeaderTitleWrapper, StyledImage, StyledTitle } from './LandingPage.styled'

export const LandingPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <StyledAppBar>
        <StyledImage src='/logo.png' alt='logo' />
        <Typography>ES HORA DE CAMBIAR</Typography>
       </StyledAppBar>
       <StyledHeader>
        <StyledHeaderImg src='/header-bcg.png' alt='header'/>
        <StyledHeaderTitleWrapper>
          <StyledTitle>
          <Typography>
          UNA VIDA SALUDABLE
        </Typography>
        <Typography>
          EMPIEZA AHORA
        </Typography>
          </StyledTitle>
        
        </StyledHeaderTitleWrapper>
        
       </StyledHeader>
      </main>

    </div>
  )
}

